### ISSUE TITLE
Posting from the BlueSky snippet raises errors with some text patterns

### ISSUE THREAD

**Issue by khinsen** [feenkcom/gt4atproto#1]
The very first message I tried to post was:
```
In strict conformance with the Scientific Method (note the capitalization!), I verify @tudorgirba.com 's affirmation that I can post to BlueSky from Glamorous Toolkit by myself. If you see this text, it works for me.
```
This raises an exception because something went wrong with processing the handle:
![Screenshot from 2023-05-26 12-53-51](https://github.com/feenkcom/gt4atproto/assets/94934/3c03c1cc-77a1-4d7e-b8d6-c208bbff4ae4)

I edited the text to remove the handle, and then wrote a second message about the error message. But `app.bsky.feed.post` also got parsed into a facet (whatever that is), and led to the same error message again.

**Comment by girba** [comment]
![2023-05-26_21-55-40_BlElement-972358656](https://github.com/feenkcom/gt4atproto/assets/249595/00792802-0604-452b-a626-85baf09c0ec4)
