### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by khinsen** [feenkcom/gt4atproto#2]
I see my own posts via an instance of `AppBskyActorDefsProfileViewDetailed`. Fine. But when I click on the avatar of a card, I get a `AppBskyActorDefsProfileViewBasic`, which has less information and in particular not the profile's posts. I tried to figure out how to get an `AppBskyActorDefsProfileViewDetailed` from the `AppBskyActorDefsProfileViewBasic`, but I didn't get very far. THere doesn't seem to be a way to see a given user's posts.

The other apparently missing (or well-hidden) data is my timeline.

**Comment by khinsen** [comment]
Noticed that if I access someone else's profile through my "following" tab, I get the detailed profile views with the posts. In principle I can construct my timeline from that. Or something better. But it would still be nice to get the detailed view for all profiles, no matter how I navigate to them.

**Comment by girba** [comment]
The thing is that when we navigate from a card to the picture we use the data we got when we requested the post data. So, whatever is in that data, that is what is spawned without requiring any extra remote call.

**Comment by khinsen** [comment]
So the more fundamental question is: it this supposed to be a moldable BlueSky client or an explainable and explorable interface to the AT protocol? Not the same priorities, not the same audience.

**Comment by girba** [comment]
As the name suggests, this project is at the level of AT Protocol first. The BlueSky snippet, for example, is built on top of that.

**Comment by hellerve** [comment]
We have picked up work on this again. The timeline now has posts  and many other views. I’ll close this for now. If/when other feature requests arise, don’t hesitate to open another issue!
